name: ProjectAgrosEnvironment
channels:
  - conda-forge
  - defaults
dependencies:
  - geopandas=0.12.2
  - jupyterlab=3.5.2
  - matplotlib=3.6.2
  - numpy=1.23.5
  - pandas=1.5.2
  - pmdarima=1.8.5
  - python=3.9.16
  - requests=2.28.1
  - seaborn=0.11.2
  - sphinx=5.0.2
  - statsmodels=0.13.1
  - typing-extensions=4.3.0

